version: 2

sphinx:
  configuration: docs/conf.py

# don't build PDF and ePub
formats: []

build:
  os: ubuntu-24.04
  tools:
    python: "3"

python:
  install:
    - requirements: docs/requirements.txt
